name: Package and deploy 
run-name: ${{ github.actor }} is testing Build and Push Image on Docker Hub 🚀
on: [push]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Pre Package
      run: chmod +x mvnw

    - name:  Install Google Chrome # Using shell script to install Google Chrome
      run: |
        chmod +x ./InstallChrome.sh
        ./InstallChrome.sh 

    - name: Run Container
      run: docker run --name auth --rm -p 8082:8082 -d amfabian/vvs-auth-api
      
    - name: Package
      run: |
        docker logout
        echo "${{ secrets.DOCKERHUB_PS }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
        ./mvnw clean package -Dquarkus.container-image.push=true -Dquarkus.jib.base-registry-password=${{ secrets.DOCKERHUB_PS }}
    
  

